<div class="easyui-accordion" fit="true" border="false">
<div title="我的设计空间" selected="true" style="overflow:auto;">
    <div class="account">
        <ul>
            <li><img src="${pageContext.request.contextPath}/static/images/ds01.png"><span style="padding:0 0 0 10px">总体设计</span>
            </li>
            <li><a href="${pageContext.request.contextPath}/mgr/xfmc/qddef"><img src="${pageContext.request.contextPath}/static/images/ds01.png"><span style="padding:0 0 0 10px">气动系统</span></a>
            </li>
            <li><a href="${pageContext.request.contextPath}/mgr/xfmc/tjdef"><img src="${pageContext.request.contextPath}/static/images/ds01.png"><span style="padding:0 0 0 10px">推进系统</span> </a>
            </li>
            <li><img src="${pageContext.request.contextPath}/static/images/ds01.png"><span style="padding:0 0 0 10px">重量</span>
            </li>
            <li><img src="${pageContext.request.contextPath}/static/images/ds01.png"><span style="padding:0 0 0 10px">飞行性能</span>
            </li>
            <li><img src="${pageContext.request.contextPath}/static/images/ds01.png"><span style="padding:0 0 0 10px">品质要素与发射平台集成</span>
            </li>
        </ul>
    </div>
</div>
<div title="型号产品结构快速索引" style="overflow:auto;">
    <ul id="pj" class="easyui-tree" animate="true" dnd="true">
        <li><span>战术导弹</span>
            <ul>
                <li><span>地对地</span>
                    <ul>
                        <li>
                            <span>型号产品001</span>
                            <ul>
                                <li>
                                    <span>总体系统</span>
                                    <ul>
                                        <li>
                                            <span>总体设计</span>
                                        </li>
                                    </ul>
                                </li>
                                <li>
                                    <span>分系统</span>
                                    <ul>
                                        <li>
                                            <span>气动系统</span>
                                        </li>
                                        <li>
                                            <span>推进系统</span>
                                        </li>
                                        <li>
                                            <span>重量</span>
                                        </li>
                                        <li>
                                            <span>飞行性能</span>
                                        </li>
                                        <li>
                                            <span>品质要素与发射平台集成</span>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                        <li state="closed">
                            <span>型号产品002</span>
                            <ul>
                                <li>
                                    <span>总体系统</span>
                                    <ul>
                                        <li>
                                            <span>总体设计</span>
                                        </li>
                                    </ul>
                                </li>
                                <li>
                                    <span>分系统</span>
                                    <ul>
                                        <li>
                                            <span>气动系统</span>
                                        </li>
                                        <li>
                                            <span>推进系统</span>
                                        </li>
                                        <li>
                                            <span>重量</span>
                                        </li>
                                        <li>
                                            <span>飞行性能</span>
                                        </li>
                                        <li>
                                            <span>品质要素与发射平台集成</span>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </li>
                <li state="closed"><span>地对空</span>
                    <ul>
                        <li>
                            <span>型号产品001</span>
                            <ul>
                                <li>
                                    <span>总体系统</span>
                                    <ul>
                                        <li>
                                            <span>总体设计</span>
                                        </li>
                                    </ul>
                                </li>
                                <li>
                                    <span>分系统</span>
                                    <ul>
                                        <li>
                                            <span>气动系统</span>
                                        </li>
                                        <li>
                                            <span>推进系统</span>
                                        </li>
                                        <li>
                                            <span>重量</span>
                                        </li>
                                        <li>
                                            <span>飞行性能</span>
                                        </li>
                                        <li>
                                            <span>品质要素与发射平台集成</span>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </li>
                <li state="closed"><span>空对空</span>
                    <ul>
                        <li>
                            <span>型号产品001</span>
                            <ul>
                                <li>
                                    <span>总体系统</span>
                                    <ul>
                                        <li>
                                            <span>总体设计</span>
                                        </li>
                                    </ul>
                                </li>
                                <li>
                                    <span>分系统</span>
                                    <ul>
                                        <li>
                                            <span>气动系统</span>
                                        </li>
                                        <li>
                                            <span>推进系统</span>
                                        </li>
                                        <li>
                                            <span>重量</span>
                                        </li>
                                        <li>
                                            <span>飞行性能</span>
                                        </li>
                                        <li>
                                            <span>品质要素与发射平台集成</span>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </li>
                <li state="closed"><span>空对地</span>
                    <ul>
                        <li>
                            <span>型号产品001</span>
                            <ul>
                                <li>
                                    <span>总体系统</span>
                                    <ul>
                                        <li>
                                            <span>总体设计</span>
                                        </li>
                                    </ul>
                                </li>
                                <li>
                                    <span>分系统</span>
                                    <ul>
                                        <li>
                                            <span>气动系统</span>
                                        </li>
                                        <li>
                                            <span>推进系统</span>
                                        </li>
                                        <li>
                                            <span>重量</span>
                                        </li>
                                        <li>
                                            <span>飞行性能</span>
                                        </li>
                                        <li>
                                            <span>品质要素与发射平台集成</span>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </li>
            </ul>
        </li>
    </ul>
</div>
</div>