{
	"rows":[
		{"id":1,"code":"弹体","grade":"","diagram":"","sureScheme":"",
          "children":[{
                "id":2,"code":"轴对称体"
            },{
                "id":3,"code":"升力体"
            }]
        },
        {"code":"头部细长比","grade":"","diagram":"","sureScheme":"",
          "children":[{
                "code":"大"
            },{
                "code":"中"
            },{
                "code":"小"
            }]
        },
        {"code":"锥形弹尾","grade":"","diagram":"","sureScheme":"",
          "children":[{
                "code":"无"
            },{
                "code":"中"
            },{
                "code":"重"
            }]
        },
        {"code":"翼（无、有）","grade":"","diagram":"","sureScheme":"",
          "children":[{
                "code":"无"
            },{
                "code":"三角形"
            },{
                "code":"后掠前沿梯形"
            },{
                "code":"前掠前沿梯形"
            },{
                "code":"矩形"
            }]
        },
        {"code":"控制方式","grade":"","diagram":"","sureScheme":"",
          "children":[{
                "code":"尾翼"
            },{
                "code":"鸭式"
            },{
                "code":"弹翼"
            },{
                "code":"非常规（推力矢量，喷流互动）"
            }]
        }
	]
}