{
	"rows":[
		{"id":1,"code":"弹体",
          "children":[{
                "id":2,"code":"轴对称体","grade":"4203.0"
            },{
                "id":3,"code":"升力体","grade":"8577.0","sureScheme":"▬"
            }]
        },
        {"code":"头部细长比",
          "children":[{
                "code":"大","grade":"8460.0","sureScheme":"〓"
            },{
                "code":"中","grade":"8625.0","sureScheme":"▬"
            },{
                "code":"小","grade":"2308.0","diagram":"","sureScheme":""
            }]
        },
        {"code":"锥形弹尾",
          "children":[{
                "code":"无","grade":"729.0"
            },{
                "code":"中","grade":"2187.0","sureScheme":"▬"
            },{
                "code":"重","grade":"243.0"
            }]
        },
        {"code":"翼（无、有）",
          "children":[{
                "code":"无","grade":"1701.0"
            },{
                "code":"三角形","grade":"2268.0","sureScheme":"〓"
            },{
                "code":"后掠前沿梯形","grade":"756.0","sureScheme":""
            },{
                "code":"前掠前沿梯形","grade":"3402.0","sureScheme":"▬"
            },{
                "code":"矩形","grade":"189.0"
            }]
        },
        {"code":"控制方式","grade":"","diagram":"","sureScheme":"",
          "children":[{
                "code":"尾翼","grade":"7401.0","sureScheme":"▬"
            },{
                "code":"鸭式","grade":"3118.0","diagram":"","sureScheme":"〓"
            },{
                "code":"弹翼","grade":"3798.0","diagram":"","sureScheme":""
            },{
                "code":"非常规（推力矢量，喷流互动）","grade":"3948.0"
            }]
        }
	]
}