{
	"rows":[
		{"id":1,"code":"导弹大径2a","targetImp":"10375.0","techTarget":"2*9.58","unit":"inches"},
        {"id":2,"code":"导弹小径2b","targetImp":"10375.0","techTarget":"9.58","unit":"inches"},
        {"id":3,"code":"头部长度","targetImp":"10290.0","techTarget":"2*9.58（4*9.58）","unit":"inches"},
        {"id":4,"code":"头部钝度","targetImp":"3375.0","techTarget":"5%（0）","unit":""},
        {"id":5,"code":"导弹长度","targetImp":"12030.0","techTarget":"11.1*9.58","unit":"inches"},
        {"code":"弹翼",
          "children":[{
                "code":"弹翼数量","targetImp":"10291.0","techTarget":"2","unit":""
            },{
                "code":"弹翼附加角","targetImp":"2997.0","techTarget":"0","unit":"deg"
            },{
                "code":"弹翼平面面积","targetImp":"783.0","techTarget":"400","unit":"inches^2"
            },{
                "code":"最大厚度弦长","targetImp":"1215.0","techTarget":"4.4%","unit":""
            },{
                "code":"弹翼前缘剖面角","targetImp":"270.0","techTarget":"10","unit":"deg"
            },{
                "code":"弹翼展弦比","targetImp":"6129.0","techTarget":"2.82","unit":""
            },{
                "code":"弹翼前缘位置","targetImp":"3609.0","techTarget":"60.8","unit":"inches"
            },{
                "code":"弹翼梢根比","targetImp":"4023.0","techTarget":"0.175","unit":""
            }]
        },
        {"code":"尾翼",
          "children":[{
                "code":"尾翼半翼展","targetImp":"9147.0","techTarget":"13.1","unit":"inches"
            },{
                "code":"尾翼根弦","targetImp":"2097.0","techTarget":"20.23","unit":"inches"
            },{
                "code":"尾翼梢弦","targetImp":"2475.0","techTarget":"0","unit":"inches"
            },{
                "code":"尾翼后掠角","targetImp":"4110.0","techTarget":"57.08","unit":"deg"
            },{
                "code":"尾翼平均气动弦长","targetImp":"2286.0","techTarget":"13.49","unit":"inches"
            },{
                "code":"尾翼气动中心（从尾翼平均气动弦）","targetImp":"4347.0","techTarget":"6.3","unit":"inches"
            },{
                "code":"尾翼气动中心（从弹头起）","targetImp":"2205.0","techTarget":"138.4","unit":"inches"
            },{
                "code":"尾翼面积","targetImp":"4368.0","techTarget":"265","unit":"inches^2"
            },{
                "code":"尾翼压心位置（从翼根起）","targetImp":"4671.0","techTarget":"4.4","unit":"inches"
            }]
        }
	]
}