{
	"rows":[
		{"id":1,"code":"性能","cusImportance":"","competingPro":"","currentPro":"","AlikePro":"","BlikePro":"","marketStr":"","graphImp":"",
          "children":[{
                "id":2,"code":"射程","cusImportance":"9.0","currentPro":"3.0","AlikePro":"4.0","BlikePro":"4.0","marketStr":"5.0"
            },{
                "id":3,"code":"飞行时间","cusImportance":"5.0","currentPro":"4.0","AlikePro":"3.0","BlikePro":"3.0","marketStr":"4.0"
            },{
                "id":4,"code":"精确度","cusImportance":"9.0","currentPro":"4.0","AlikePro":"4.0","BlikePro":"5.0","marketStr":"5.0"
            },{
                "id":5,"code":"可靠性","cusImportance":"5.0","currentPro":"3.0","AlikePro":"4.0","BlikePro":"4.0","marketStr":"4.0"
            },{
                "id":6,"code":"耐受性","cusImportance":"9.0","currentPro":"4.0","AlikePro":"4.0","BlikePro":"5.0","marketStr":"5.0"
            }]
        },
        {"id":7,"code":"业务营运",
          "children":[{
                "id":8,"code":"通用性","cusImportance":"9.0","currentPro":"3.0","AlikePro":"4.0","BlikePro":"4.0","marketStr":"5.0"
            },{
                "id":9,"code":"运输性","cusImportance":"1.0","currentPro":"4.0","AlikePro":"3.0","BlikePro":"3.0","marketStr":"4.0"
            },{
                "id":10,"code":"操作安全性","cusImportance":"9.0","currentPro":"4.0","AlikePro":"5.0","BlikePro":"4.0","marketStr":"5.0"
            },{
                "id":11,"code":"作战毁伤评估","cusImportance":"3.0","currentPro":"3.0","AlikePro":"4.0","BlikePro":"4.0","marketStr":"4.0"
            },{
                "id":12,"code":"贮藏方式","cusImportance":"5.0","currentPro":"3.0","AlikePro":"4.0","BlikePro":"4.0","marketStr":"4.0"
            }]
        },
        {"id":13,"code":"造价",
          "children":[{
                "id":14,"code":"实验和鉴定成本","cusImportance":"3.0","currentPro":"2.0","AlikePro":"4.0","BlikePro":"3.0","marketStr":"4.0"
            },{
                "id":15,"code":"购置成本","cusImportance":"9.0","currentPro":"3.0","AlikePro":"5.0","BlikePro":"5.0","marketStr":"5.0"
            },{
                "id":16,"code":"支持费用","cusImportance":"9.0","currentPro":"3.0","AlikePro":"4.0","BlikePro":"5.0","marketStr":"5.0"
            },{
                "id":17,"code":"处理费用","cusImportance":"1.0","currentPro":"3.0","AlikePro":"3.0","BlikePro":"3.0","marketStr":"3.0"
            }]
        }
	]
}