[{
	"id":1,
	"characteristics":"推进",
	"dirOfImp":"",
	"weightImp":"",
	"risk":"",
    "relOfImp":"",
	"target":"",
	"iconCls":"icon-ok",
	"children":[{
		"id":2,
	    "characteristics":"推重",
	    "dirOfImp":"",
	    "weightImp":"",
	    "risk":"",
        "relOfImp":"",
	    "target":"",
        "state":"closed",
        "children":[{
		    "id":3,
	        "characteristics":"爬升能力",
	        "dirOfImp":"↑",
	        "weightImp":"",
	        "risk":"",
	        "relOfImp":"",
	        "target":""
	    }]
	},{
		"id":4,
	    "characteristics":"燃料效能",
	    "dirOfImp":"",
	    "weightImp":"",
	    "risk":"",
        "relOfImp":"",
	    "target":"",
        "state":"closed",
        "children":[{
		    "id":5,
	        "characteristics":"SFC燃油消耗率",
	         "dirOfImp":"↓",
	         "weightImp":"",
	         "risk":"",
             "relOfImp":"",
	         "target":""
	    }]
	}]
},
{
	"id":6,
	"characteristics":"弹体技术",
	"dirOfImp":"",
	"weightImp":"",
	"risk":"",
    "relOfImp":"",
	"target":"",
	"iconCls":"icon-ok",
	"children":[{
		"id":7,
	    "characteristics":"材料与结构",
	    "dirOfImp":"",
	    "weightImp":"",
	    "risk":"",
        "relOfImp":"",
	    "target":"",
        "state":"closed",
        "children":[{
		    "id":8,
	        "characteristics":"材料强度",
	         "dirOfImp":"↑",
	         "weightImp":"",
	         "risk":"",
             "relOfImp":"",
	         "target":""
	    },{
		    "id":9,
	        "characteristics":"结构重量",
	         "dirOfImp":"↓",
	         "weightImp":"",
	         "risk":"",
             "relOfImp":"",
	         "target":""
	    }]
	},{
		"id":10,
	    "characteristics":"空气动力学",
	    "dirOfImp":"",
	    "weightImp":"",
	    "risk":"",
        "relOfImp":"",
	    "target":"",
        "state":"closed",
          "children":[{
		    "id":8,
	        "characteristics":"长度直径比",
	         "dirOfImp":"",
	         "weightImp":"",
	         "risk":"",
             "relOfImp":"",
	         "target":""
	    },{
		    "id":9,
	        "characteristics":"横截面面积",
	         "dirOfImp":"↓",
	         "weightImp":"",
	         "risk":"",
             "relOfImp":"",
	         "target":""
	    }]
	},{
		"id":13,
	    "characteristics":"尺寸",
	    "dirOfImp":"",
	    "weightImp":"",
	    "risk":"",
        "relOfImp":"",
	    "target":"",
        "state":"closed",
        "children":[{
		    "id":14,
	        "characteristics":"燃油量",
	        "dirOfImp":"↓",
	        "weightImp":"",
	        "risk":"",
	        "relOfImp":"",
	        "target":""
	    }]
	}]
},{
	"id":15,
	"characteristics":"制导系统",
	"dirOfImp":"",
	"weightImp":"",
	"risk":"",
    "relOfImp":"",
	"target":" ",
	"iconCls":"icon-ok",
	"children":[{
		"id":16,
	    "characteristics":"导航",
	    "dirOfImp":"",
	    "weightImp":"",
	    "risk":"",
        "relOfImp":"",
	    "target":"",
        "state":"closed",
          "children":[{
		    "id":17,
	        "characteristics":"航空电子技术",
	         "dirOfImp":"↑",
	         "weightImp":"",
	         "risk":"",
             "relOfImp":"",
	         "target":""
	    },{
		    "id":18,
	        "characteristics":"概率圆误差",
	         "dirOfImp":"↓",
	         "weightImp":"",
	         "risk":"",
             "relOfImp":"",
	         "target":""
	    },{
		    "id":19,
	        "characteristics":"信号延迟时间",
	         "dirOfImp":"↓",
	         "weightImp":"",
	         "risk":"",
             "relOfImp":"",
	         "target":""
	    }]
	},{
		"id":20,
	    "characteristics":"机动性",
	    "dirOfImp":"",
	    "weightImp":"",
	    "risk":"",
        "relOfImp":"",
	    "target":"",
        "state":"closed",
          "children":[{
		    "id":21,
	        "characteristics":"控制系统",
	         "dirOfImp":"×",
	         "weightImp":"",
	         "risk":"",
             "relOfImp":"",
	         "target":""
	    }]
	}]
},{
	"id":22,
	"characteristics":"操作",
	"dirOfImp":"",
	"weightImp":"",
	"risk":"",
    "relOfImp":"",
	"target":"",
	"iconCls":"icon-ok",
	"children":[{
		"id":23,
	    "characteristics":"符合性",
	    "dirOfImp":"",
	    "weightImp":"",
	    "risk":"",
        "relOfImp":"",
	    "target":"",
        "state":"closed",
          "children":[{
		    "id":24,
	        "characteristics":"非敏感性弹药",
	         "dirOfImp":"",
	         "weightImp":"",
	         "risk":"",
             "relOfImp":"",
	         "target":""
	    }]
	},{
		"id":25,
	    "characteristics":"后勤",
	    "dirOfImp":"",
	    "weightImp":"",
	    "risk":"",
        "relOfImp":"",
	    "target":"",
        "state":"closed",
          "children":[{
		    "id":26,
	        "characteristics":"维护",
	         "dirOfImp":"↓",
	         "weightImp":"",
	         "risk":"",
             "relOfImp":"",
	         "target":""
	    },{
		    "id":27,
	        "characteristics":"库存时间",
	         "dirOfImp":"↑",
	         "weightImp":"",
	         "risk":"",
             "relOfImp":"",
	         "target":""
	    }]
	}]
},
{
	"id":28,
	"characteristics":"任务效能",
	"dirOfImp":"",
	"weightImp":"",
	"risk":"",
    "relOfImp":"",
	"target":"",
	"iconCls":"icon-ok",
	"children":[{
		"id":29,
	    "characteristics":"被探测性",
	    "dirOfImp":"",
	    "weightImp":"",
	    "risk":"",
        "relOfImp":"",
	    "target":"",
        "state":"closed",
          "children":[{
		    "id":30,
	        "characteristics":"雷达目标有效截面",
	         "dirOfImp":"↓",
	         "weightImp":"",
	         "risk":"",
             "relOfImp":"",
	         "target":""
	    },{
		    "id":31,
	        "characteristics":"可见度",
	         "dirOfImp":"↓",
	         "weightImp":"",
	         "risk":"",
             "relOfImp":"",
	         "target":""
        },{
		    "id":32,
	        "characteristics":"红外线标签",
	         "dirOfImp":"↓",
	         "weightImp":"",
	         "risk":"",
             "relOfImp":"",
	         "target":""
	    },{
		    "id":33,
	        "characteristics":"信号覆盖区",
	         "dirOfImp":"↓",
	         "weightImp":"",
	         "risk":"",
             "relOfImp":"",
	         "target":""
	    }]
	},{
		"id":34,
	    "characteristics":"被击中性",
	    "dirOfImp":"",
	    "weightImp":"",
	    "risk":"",
        "relOfImp":"",
	    "target":"",
        "state":"closed",
          "children":[{
		    "id":35,
	        "characteristics":"高度",
	         "dirOfImp":"↑",
	         "weightImp":"",
	         "risk":"",
             "relOfImp":"",
	         "target":""
	    },{
		    "id":36,
	        "characteristics":"速度",
	         "dirOfImp":"↑",
	         "weightImp":"",
	         "risk":"",
             "relOfImp":"",
	         "target":""
	    }]
	},{
		"id":37,
	    "characteristics":"系统性能",
	    "dirOfImp":"",
	    "weightImp":"",
	    "risk":"",
        "relOfImp":"",
	    "target":"",
        "state":"closed",
          "children":[{
		    "id":38,
	        "characteristics":"反应时间",
	         "dirOfImp":"↓",
	         "weightImp":"",
	         "risk":"",
             "relOfImp":"",
	         "target":""
	    },{
		    "id":39,
	        "characteristics":"毁灭性",
	         "dirOfImp":"↑",
	         "weightImp":"",
	         "risk":"",
             "relOfImp":"",
	         "target":""
	    },{
		    "id":40,
	        "characteristics":"弹道轨迹",
	         "dirOfImp":"",
	         "weightImp":"",
	         "risk":"",
             "relOfImp":"",
	         "target":""
	    }]
	},{
		"id":41,
	    "characteristics":"机动性",
	    "dirOfImp":"",
	    "weightImp":"",
	    "risk":" ",
        "relOfImp":"",
	    "target":"",
        "state":"closed",
          "children":[{
		    "id":42,
	        "characteristics":"回转半径",
	         "dirOfImp":"↓",
	         "weightImp":"",
	         "risk":"",
             "relOfImp":"",
	         "target":""
	    }]
	}]
}]