{
	"rows":[
		{"id":1,"code":"性能","propulsion":"","thrustToWeigh":"","ClimbCapability":"","FuelEfficiency":"","SFC":"",
                "AirframeTech":"","MaterialsStructures":"","MaterialStrength":"","StructuralWeight":"","Aerodynamics":"","L/D":"","CrossSectionArea":"",
                "Size":"","FuelVolume":"","GNC":"","GuidanceNavigation":"","AvionicsTechnology":"","CircleErrorProbable":"",
                "SignalTimeDelay":"","cusAssessment":"","Maneuverability":"","Operations":"","IMComplianceIM":"","InsensitiveMunitions":"",
                "Logistics":"","Maintenance":"","DepotLife":"","MissionEffec":"","BeingDetected":"","RadarCrossSection":"",
                "Visibility":"","Infra-redSignature":"","Footprint/Noise":"","BeingHit":"","Altitude":"","Speed":"",
                "SystemCapability":"","ResponseTime":"","Lethality":"","Trajectory":"","Maneuverability":"","TurnRadius":"",
          "children":[{
                "id":2,"code":"射程","ClimbCapability":"●","SFC":"●","StructuralWeight":"○","L/D":"○","CrossSectionArea":"●",
                "FuelVolume":"●","Altitude":"○","Speed":"●","Trajectory":"○"
            },{
                "id":3,"code":"飞行时间","ClimbCapability":"●","SFC":"●","L/D":"○","CrossSectionArea":"○","AvionicsTechnology":"△",
                "SignalTimeDelay":"△","Altitude":"○","Speed":"●","Trajectory":"●"
            },{
                "id":4,"code":"精确度","L/D":"△","AvionicsTechnology":"●","CircleErrorProbable":"●","SignalTimeDelay":"●","ControlSystem":"●",
                "Altitude":"△","Trajectory":"△","TurnRadius":"○"
            },{
                "id":6,"code":"可靠性","MaterialStrength":"●","AvionicsTechnology":"△","CircleErrorProbable":"●","SignalTimeDelay":"○","ControlSystem":"○",
                "DepotLife":"△","ResponseTime":"○","Lethality":"○","TurnRadius":"●"
            },{
                "id":5,"code":"耐受性","ClimbCapability":"○","CrossSectionArea":"△",
                "AvionicsTechnology":"○",
                "SignalTimeDelay":"△","ControlSystem":"○",
                "RadarCrossSection":"●",
                "Visibility":"●","Infra-redSignature":"●","Footprint/Noise":"●","Altitude":"●","Speed":"●",
                "Trajectory":"△","TurnRadius":"△"
            }]
        },
        {"id":7,"code":"业务营运",
          "children":[{
                "id":8,"code":"通用性","StructuralWeight":"△","CrossSectionArea":"●","FuelVolume":"○","AvionicsTechnology":"●","InsensitiveMunitions":"○",
                "Maintenance":"○","DepotLife":"△"
            },{
                "id":9,"code":"运输性","MaterialStrength":"△","StructuralWeight":"△","CrossSectionArea":"△","FuelVolume":"△","InsensitiveMunitions":"○",
                "DepotLife":"○"
            },{
                "id":10,"code":"操作安全性","MaterialStrength":"△","InsensitiveMunitions":"●",
                "Maintenance":"△","DepotLife":"△"
            },{
                "id":12,"code":"作战毁伤评估","AvionicsTechnology":"○","CircleErrorProbable":"○","SignalTimeDelay":"○","Trajectory":"○"
            },{
                "id":11,"code":"贮藏方式","AvionicsTechnology":"○","InsensitiveMunitions":"○","Maintenance":"○","DepotLife":"●"
            }]
        },
        {"id":13,"code":"造价",
          "children":[{
                "id":14,"code":"实验和鉴定成本","ClimbCapability":"●","SFC":"●","MaterialStrength":"●","StructuralWeight":"○","L/D":"○","CrossSectionArea":"○",
                "FuelVolume":"△","AvionicsTechnology":"●","CircleErrorProbable":"●","SignalTimeDelay":"○","ControlSystem":"○","InsensitiveMunitions":"○",
                "Maintenance":"△","DepotLife":"○","RadarCrossSection":"●","Visibility":"●","Infra-redSignature":"●","Footprint/Noise":"●","Altitude":"○",
                "Speed":"○","ResponseTime":"△","Lethality":"●","Trajectory":"○","TurnRadius":"●"
            },{
                "id":15,"code":"购置成本","ClimbCapability":"△","SFC":"○","MaterialStrength":"●","StructuralWeight":"●","L/D":"○","CrossSectionArea":"○",
                "FuelVolume":"●","AvionicsTechnology":"●","CircleErrorProbable":"○","SignalTimeDelay":"△","ControlSystem":"△","InsensitiveMunitions":"●",
                "Maintenance":"△","DepotLife":"△","RadarCrossSection":"●","Visibility":"△","Infra-redSignature":"●","Footprint/Noise":"●","Altitude":"○",
                "Speed":"○","ResponseTime":"△","Lethality":"●","Trajectory":"○","TurnRadius":"●"
            },{
                "id":16,"code":"支持费用","FuelVolume":"○","AvionicsTechnology":"△","InsensitiveMunitions":"●","Maintenance":"○","DepotLife":"○"
            },{
                "id":17,"code":"处理费用","StructuralWeight":"○",
                "FuelVolume":"○","InsensitiveMunitions":"●"
            }]
        }
	]
}