[{
	"id":1,
	"characteristics":"推进",
	"wpfdj":"",
	"cyfdj":"",
	"hdshj":"",
    "crfdj":"",
	"gthjfdj":"",
	"iconCls":"icon-ok",
	"children":[{
		"id":2,
	    "characteristics":"推重",
	    "wpfdj":"",
	    "cyfdj":"",
	    "hdshj":"",
        "crfdj":"",
	    "gthjfdj":"",
        "state":"closed",
        "children":[{
		    "id":3,
	        "characteristics":"爬升能力",
	        "wpfdj":"△",
	        "cyfdj":"●",
	        "hdshj":"○",
	        "crfdj":"○",
	        "gthjfdj":"○"
	    }]
	},{
		"id":4,
	    "characteristics":"燃料效能",
	    "wpfdj":"",
	    "cyfdj":"",
	    "hdshj":"",
        "crfdj":"",
	    "gthjfdj":"",
        "state":"closed",
        "children":[{
		    "id":5,
	        "characteristics":"SFC燃油消耗率",
	         "wpfdj":"△",
	         "cyfdj":"●",
	         "hdshj":"○",
             "crfdj":"●",
	         "gthjfdj":"●"
	    }]
	}]
},
{
	"id":6,
	"characteristics":"弹体技术",
	"wpfdj":"",
	"cyfdj":"",
	"hdshj":"",
    "crfdj":"",
	"gthjfdj":"",
	"iconCls":"icon-ok",
	"children":[{
		"id":7,
	    "characteristics":"材料与结构",
	    "wpfdj":"",
	    "cyfdj":"",
	    "hdshj":"",
        "crfdj":"",
	    "gthjfdj":"",
        "state":"closed",
        "children":[{
		    "id":8,
	        "characteristics":"材料强度",
	         "wpfdj":"",
	         "cyfdj":"",
	         "hdshj":"",
             "crfdj":"",
	         "gthjfdj":""
	    },{
		    "id":9,
	        "characteristics":"结构重量",
	         "wpfdj":"",
	         "cyfdj":"",
	         "hdshj":"",
             "crfdj":"",
	         "gthjfdj":""
	    }]
	},{
		"id":10,
	    "characteristics":"空气动力学",
	    "wpfdj":"",
	    "cyfdj":"",
	    "hdshj":"",
        "crfdj":"",
	    "gthjfdj":"",
        "state":"closed",
          "children":[{
		    "id":8,
	        "characteristics":"长度直径比",
	         "wpfdj":"●",
	         "cyfdj":"○",
	         "hdshj":"○",
             "crfdj":"△",
	         "gthjfdj":"○"
	    },{
		    "id":9,
	        "characteristics":"横截面面积",
	         "wpfdj":"",
	         "cyfdj":"",
	         "hdshj":"",
             "crfdj":"",
	         "gthjfdj":""
	    }]
	},{
		"id":13,
	    "characteristics":"尺寸",
	    "wpfdj":"",
	    "cyfdj":"",
	    "hdshj":"",
        "crfdj":"",
	    "gthjfdj":"",
        "state":"closed",
        "children":[{
		    "id":14,
	        "characteristics":"燃油量",
	        "wpfdj":"△",
	        "cyfdj":"●",
	        "hdshj":"●",
	        "crfdj":"○",
	        "gthjfdj":"△"
	    }]
	}]
},{
	"id":15,
	"characteristics":"制导系统",
	"wpfdj":"",
	"cyfdj":"",
	"hdshj":"",
    "crfdj":"",
	"gthjfdj":" ",
	"iconCls":"icon-ok",
	"children":[{
		"id":16,
	    "characteristics":"导航",
	    "wpfdj":"",
	    "cyfdj":"",
	    "hdshj":"",
        "crfdj":"",
	    "gthjfdj":"",
        "state":"closed",
          "children":[{
		    "id":17,
	        "characteristics":"航空电子技术",
	         "wpfdj":"",
	         "cyfdj":"",
	         "hdshj":"",
             "crfdj":"",
	         "gthjfdj":""
	    },{
		    "id":18,
	        "characteristics":"概率圆误差",
	         "wpfdj":"",
	         "cyfdj":"",
	         "hdshj":"",
             "crfdj":"",
	         "gthjfdj":""
	    },{
		    "id":19,
	        "characteristics":"信号延迟时间",
	         "wpfdj":"",
	         "cyfdj":"",
	         "hdshj":"",
             "crfdj":"",
	         "gthjfdj":""
	    }]
	},{
		"id":20,
	    "characteristics":"机动性",
	    "wpfdj":"",
	    "cyfdj":"",
	    "hdshj":"",
        "crfdj":"",
	    "gthjfdj":"",
        "state":"closed",
          "children":[{
		    "id":21,
	        "characteristics":"控制系统",
	         "wpfdj":"",
	         "cyfdj":"",
	         "hdshj":"",
             "crfdj":"",
	         "gthjfdj":""
	    }]
	}]
},{
	"id":22,
	"characteristics":"操作",
	"wpfdj":"",
	"cyfdj":"",
	"hdshj":"",
    "crfdj":"",
	"gthjfdj":"",
	"iconCls":"icon-ok",
	"children":[{
		"id":23,
	    "characteristics":"符合性",
	    "wpfdj":"",
	    "cyfdj":"",
	    "hdshj":"",
        "crfdj":"",
	    "gthjfdj":"",
        "state":"closed",
          "children":[{
		    "id":24,
	        "characteristics":"非敏感性弹药",
	         "wpfdj":"",
	         "cyfdj":"",
	         "hdshj":"",
             "crfdj":"",
	         "gthjfdj":""
	    }]
	},{
		"id":25,
	    "characteristics":"后勤",
	    "wpfdj":"",
	    "cyfdj":"",
	    "hdshj":"",
        "crfdj":"",
	    "gthjfdj":"",
        "state":"closed",
          "children":[{
		    "id":26,
	        "characteristics":"维护",
	         "wpfdj":"",
	         "cyfdj":"",
	         "hdshj":"",
             "crfdj":"",
	         "gthjfdj":""
	    },{
		    "id":27,
	        "characteristics":"库存时间",
	         "wpfdj":"",
	         "cyfdj":"",
	         "hdshj":"",
             "crfdj":"",
	         "gthjfdj":""
	    }]
	}]
},
{
	"id":28,
	"characteristics":"任务效能",
	"wpfdj":"",
	"cyfdj":"",
	"hdshj":"",
    "crfdj":"",
	"gthjfdj":"",
	"iconCls":"icon-ok",
	"children":[{
		"id":29,
	    "characteristics":"被探测性",
	    "wpfdj":"",
	    "cyfdj":"",
	    "hdshj":"",
        "crfdj":"",
	    "gthjfdj":"",
        "state":"closed",
          "children":[{
		    "id":30,
	        "characteristics":"雷达目标有效截面",
	         "wpfdj":"",
	         "cyfdj":"",
	         "hdshj":"",
             "crfdj":"",
	         "gthjfdj":""
	    },{
		    "id":31,
	        "characteristics":"可见度",
	         "wpfdj":"",
	         "cyfdj":"",
	         "hdshj":"",
             "crfdj":"",
	         "gthjfdj":""
	    },{
		    "id":32,
	        "characteristics":"红外线标签",
	         "wpfdj":"",
	         "cyfdj":"",
	         "hdshj":"",
             "crfdj":"",
	         "gthjfdj":""
	    },{
		    "id":33,
	        "characteristics":"信号覆盖区",
	         "wpfdj":"",
	         "cyfdj":"",
	         "hdshj":"",
             "crfdj":"",
	         "gthjfdj":""
	    }]
	},{
		"id":34,
	    "characteristics":"被击中性",
	    "wpfdj":"",
	    "cyfdj":"",
	    "hdshj":"",
        "crfdj":"",
	    "gthjfdj":"",
        "state":"closed",
          "children":[{
		    "id":35,
	        "characteristics":"高度",
	         "wpfdj":"○",
	         "cyfdj":"○",
	         "hdshj":"○",
             "crfdj":"○",
	         "gthjfdj":"○"
	    },{
		    "id":36,
	        "characteristics":"速度",
	         "wpfdj":"△",
	         "cyfdj":"○",
	         "hdshj":"○",
             "crfdj":"●",
	         "gthjfdj":"○"
	    }]
	},{
		"id":37,
	    "characteristics":"系统性能",
	    "wpfdj":"",
	    "cyfdj":"",
	    "hdshj":"",
        "crfdj":"",
	    "gthjfdj":"",
        "state":"closed",
          "children":[{
		    "id":38,
	        "characteristics":"反应时间",
	         "wpfdj":"",
	         "cyfdj":"",
	         "hdshj":"",
             "crfdj":"",
	         "gthjfdj":""
	    },{
		    "id":39,
	        "characteristics":"毁灭性",
	         "wpfdj":"",
	         "cyfdj":"",
	         "hdshj":"",
             "crfdj":"",
	         "gthjfdj":""
	    },{
		    "id":40,
	        "characteristics":"弹道轨迹",
	         "wpfdj":"",
	         "cyfdj":"",
	         "hdshj":"",
             "crfdj":"",
	         "gthjfdj":""
	    }]
	},{
		"id":41,
	    "characteristics":"机动性",
	    "wpfdj":"",
	    "cyfdj":"",
	    "hdshj":" ",
        "crfdj":"",
	    "gthjfdj":"",
        "state":"closed",
          "children":[{
		    "id":42,
	        "characteristics":"回转半径",
	         "wpfdj":"",
	         "cyfdj":"",
	         "hdshj":"",
             "crfdj":"",
	         "gthjfdj":""
	    }]
	}]
}]