{
	"rows":[
		{"id":1,"code":"助推发动机",
          "children":[{
                "id":2,"code":"助推发动机类型","direction":"×","techImport":"5695.0","targetVal":"固体火箭"
            },{
                "code":"燃烧类型","direction":"↑","techImport":"3861.0","targetVal":"高燃速"
            },{
                "code":"燃烧室压强","direction":"×","techImport":"4266.0","targetVal":"1769","unit":"psi"
            },{
                "code":"喷管膨胀比","direction":"↑","techImport":"369.0","targetVal":"6"
            },{
                "code":"助推燃烧时间","direction":"↑","techImport":"1593.0","targetVal":"3.26","unit":"sec"
            },{
                "code":"发射高度","direction":"×","techImport":"3699.0","targetVal":"20000","unit":"feet"
            },{
                "code":"助推系统重量","direction":"×","techImport":"1857.0","targetVal":"84.8","unit":"ibm"
            },{
                "code":"参考面积","direction":"×","techImport":"2172.0","targetVal":"72.11","unit":"inchesˆ2"
            },{
                "code":"助推器比冲","direction":"↑","techImport":"2667.0","targetVal":"238","unit":"sec"
            },{
                "code":"助推器推力","direction":"↑","techImport":"2595.0","targetVal":"7000","unit":"ibf"
            }]
        },
        {"code":"巡航续航发动机",
          "children":[{
                "code":"巡航发动机","direction":"×","techImport":"4665.0","targetVal":"冲压发动机"
            },{
                "code":"燃烧热值","direction":"↑","techImport":"4482.0","targetVal":"15535588.25","unit":"ft-ibf/ibm"
            },{
                "code":"燃烧室温度","direction":"↑","techImport":"2080.0","targetVal":"4000","unit":"Rankine"
            },{
                "code":"巡航开始速度","direction":"×","techImport":"2637.0","targetVal":"2.31","unit":"Ma"
            },{
                "code":"巡航发动机比冲","direction":"↑","techImport":"5103.0","targetVal":"250","unit":"sec"
            },{
                "code":"巡航发动机推力","direction":"↑","techImport":"5334.0","targetVal":"1018","unit":"ibf"
            },{
                "code":"出口压强","direction":"↑","techImport":"3916.0","targetVal":"45","unit":"psi"
            },{
                "code":"巡航喷喉面积","direction":"×","techImport":"2244.0","targetVal":"2.4","unit":"inchesˆ2"
            },{
                "code":"巡航喷口出口面积","direction":"×","techImport":"6069.0","targetVal":"14.5","unit":"inchesˆ2"
            }]
        },
        {"code":"一体化方案",
          "children":[{
                "code":"整体式","techImport":"6051.0","targetVal":"整体式"
            },{
                "code":"后置助推器（分离）","techImport":"189.0"
            },{
                "code":"前置助推器","techImport":"1236.0"
            },{
                "code":"吊舱式助推器（分离）","techImport":"1059.0"
            },{
                "code":"吊舱式冲压发动机","techImport":"669.0"
            }]
        }
	]
}