{"total":6,"rows":[
{"name":"型号代号","value":"123-456-7890","group":"型号基本信息","editor":"text"},
{"name":"型号名称","value":"","group":"型号基本信息","editor":"text"},
{"name":"型号构建时间","value":"01/07/2011","group":"型号基本信息","editor":"datebox"},
{"name":"设计结束时间","value":"01/09/2011","group":"型号基本信息","editor":"datebox"},
{"name":"联系方式","value":"bill@gmail.com","group":"型号基本信息","editor":{
"type":"validatebox",
"options":{
"validType":"email"
}
}},
{"name":"是否类似构建","value":"false","group":"型号基本信息","editor":{
"type":"checkbox",
"options":{
"on":true,
"off":false
}
}}
]}